/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the dart mavlink generator tool. 
 * It should not be modified by hand.
 */

import 'mavlink_packet.dart';
import 'mavlink_payload.dart';

/// Common interface for all MAVLink messages
abstract class MAVLinkMessage {
  int sysid = 0;
  int compid = 0;
  int msgid = 0;
  bool isMavlink2 = false;

  MAVLinkPacket pack();
  void unpack(MAVLinkPayload payload);
  String msgName();
}
